Repository LucasTesnier/Ftrace, pull requests merged in 2022-04, with the labels that each got.

#13 Setup - Architecture - Fixing base architecture
  Makefile
  include/ftrace_init.h
  src/ftrace_start.c
  src/main.c
Labels: bug, Tech Adding

#15 Error Handling - Verify the provided arguments
  Makefile
  include/ftrace_error_handling.h
  include/ftrace_start.h
  src/ftrace_error_handling.c
  src/ftrace_start.c
  src/main.c
Labels: bug, Tech Adding

#14 ELF Lib - Open file
  Makefile
  include/elf_open.h
  include/ftrace_init.h
  src/elf_lib/elf_open.c
  src/ftrace_init.c
  src/main.c
Labels: documentation, Tech Adding, Coding style

#16 Lib Elf Adress - Match the ELF Adress
  Makefile
  include/elf_adress.h
  include/utils.h
  src/elf_lib/elf_adress.c
  src/elf_lib/elf_open.c
  src/ftrace_start.c
  src/utils.c
Labels: documentation, Tech Adding, Coding style

#17 Strace implementation
  Makefile
  include/ftrace_prepare_command.h
  include/ftrace_prepare_path.h
  include/ftrace_signals.h
  include/ftrace_start.h
  include/ftrace_syscall.h
  include/ftrace_trace_command.h
  src/ftrace_prepare_command.c
  src/ftrace_prepare_path.c
  src/ftrace_signals.c
  src/ftrace_start.c
  src/ftrace_trace_command.c
  src/main.c
Labels: documentation, Tech Improving

#18 Develop
  .github/workflows/main.yml
  Makefile
  include/elf_adress.h
  include/elf_open.h
  include/ftrace_error_handling.h
  include/ftrace_prepare_command.h
  include/ftrace_prepare_path.h
  include/ftrace_signals.h
  include/ftrace_start.h
  include/ftrace_syscall.h
  include/ftrace_trace_command.h
  include/utils.h
  src/elf_lib/elf_adress.c
  src/elf_lib/elf_open.c
  src/ftrace_error_handling.c
  src/ftrace_init.c
  src/ftrace_prepare_command.c
  src/ftrace_prepare_path.c
  src/ftrace_signals.c
  src/ftrace_start.c
  src/ftrace_trace_command.c
  src/main.c
  src/utils.c
Labels: documentation, Tech Adding, Coding style

#21 Function Gestion - Refactoring - Fixing unknown function display #6
  src/ftrace_trace_command.c
  src/function/function_init.c
Labels: Tech Improving, Tech Adding

#22 Epitech copliant style
  Makefile
  include/ftrace_process_rip.h
  src/ftrace_process_rip.c
  src/ftrace_trace_command.c
  src/function/function_init.c
  src/utils.c
Labels: bug, documentation, Tech Improving, Coding style

#23 Signals - Adding - Display received signals #8
  Makefile
  include/ftrace_received_signals.h
  src/ftrace_received_signals.c
  src/ftrace_trace_command.c
Labels: documentation, Tech Adding

#24 Fixing Many Bugs
  src/ftrace_start.c
  src/ftrace_trace_command.c
Labels: bug, Tech Improving
